name: python38
version: '3.8.0'
base: core18
summary: Python 3.8
description: |
  Python 3.8

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

apps:
  python38:
    command: python3.8
    environment:
      PYTHONPYCACHEPREFIX: $SNAP_DATA/pycache
      PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.8/site-packages
    plugs:
      - network
      - home

parts:
  python38:
    plugin: nil
    stage-packages:
      - python3.8
      - python3.8-distutils
    override-build: |
      snapcraftctl build
      /bin/bash -c "/usr/bin/python3.8 <(wget -q -O - https://bootstrap.pypa.io/get-pip.py) --prefix $SNAPCRAFT_PART_INSTALL"
    build-packages:
      - wget
      - python3.8
      - python3.8-distutils
