name: python38
version: '3.8.0'
base: core18
summary: Python 3.8
description: |
  Python 3.8

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

apps:
  python38:
    command: python
    environment:
      PYTHONPYCACHEPREFIX: $SNAP_DATA/pycache
    plugs:
      - home

parts:
  python38:
    plugin: py38
    python-packages:
      - __none__
